# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee2969c735c08fe019baac772fe857eb8fa0af5f1bbf6bd913d8ebc2b68df933744cc81319f626c9aa3a05b85a15eb58af7522b8bea875cbb2fe1e6e6f7361aa

test:
  secret_key_base: 0edc69b1edd63d25eb68ba0a7840a62d0247406db24928c5f3a96e52041591491c65b4739cce997cc3d64df175f4cc9fd40d1f210d0339827afafe38457ec556

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
